# Generated by Django 5.0 on 2024-04-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stol',
            name='number',
            field=models.IntegerField(),
        ),
    ]
