# Generated by Django 5.0 on 2024-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stol_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stol',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
