# Generated by Django 5.0 on 2024-04-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cart_stol_alter_cart_waiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stol',
            name='number',
            field=models.IntegerField(),
        ),
    ]
