# Generated by Django 5.0.3 on 2024-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_waiter_remove_stol_num_product_quantity_stol_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(max_length=20),
        ),
    ]
