# Generated by Django 5.0 on 2024-04-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cart_products_alter_cart_stol'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.cart'),
        ),
    ]
