# Generated by Django 5.0 on 2024-04-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='carts',
        ),
    ]
